### ISSUE TITLE
Crash rendering tooltip for spawner

### ISSUE THREAD

**Issue by djnifos** [Shadows-of-Fire/Apothic-Spawners#5]
Neo 21.1.8
Apothic Spawners 1.21-1.0.2
Placebo 1.21-9.3.5

Any time the item is hovered over in the inventory, it crashes.  I was able to remove it from my inventory using other mods. If you need me to get any other information, I am willing to help

https://mclo.gs/ddyIHKV

**Comment by Shadows-of-Fire** [comment]
e2200a8ec5b8967b7e34c2b75473ba5384cc2c86
